"""Add details JSON column to Donation model

Revision ID: d2e598fddd78
Revises: 
Create Date: 2025-03-18 16:09:51.976945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e598fddd78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.JSON(), nullable=True))
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('book_type')
        batch_op.drop_column('medical_type')
        batch_op.drop_column('food_type')
        batch_op.drop_column('size')
        batch_op.drop_column('pet_age')
        batch_op.drop_column('special_instructions')
        batch_op.drop_column('pet_type')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pet_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('special_instructions', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pet_age', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('food_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('medical_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('book_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('details')

    # ### end Alembic commands ###
